<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>NativeSpy.Protocol.Json</AssemblyName>
    <RootNamespace>NativeSpy.Protocol.Json</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
    <ProjectReference Include="..\NativeSpy.Protocol\NativeSpy.Protocol.csproj" />
  </ItemGroup>
</Project>
